openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
  description: API for testing K6

servers:
  - url: https://jsonplaceholder.typicode.com
    description: Public Test API

paths:
  /users:
    get:
      summary: Get all users
      operationId: getUsers
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
