name: K6 Load Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate K6 Test Script
        run: npm run generate-k6

      - name: Run K6 Load Test
        run: npm run run-k6
