name: pvs/gradle
on:
  workflow_dispatch:
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
  Build:
    runs-on: ubuntu-latest
    needs: Checkout
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: sh
      shell: bash
      run: java --version
    - name: sh
      shell: bash
      run: gradle --version
    - name: sh
      shell: bash
      run: gradle clean build
