name: Java CI with Gradle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4 # v4.0.0
      with:
        gradle-version: '8.5'
        
    - name: Build
      run: gradle build

    - name: Deploy
      run: gradle run

    - name: Setup K6
      uses: grafana/setup-k6-action@v1
    - name: Run local k6 test
      uses: grafana/run-k6-action@v1
      with:
        path: test.js
